Feature/20 social login kakao google
14-team13/acoe-backend pull request #33
Opened 2023-04-22 07:01 UTC by Hanseunghoon

소셜 로그인 (카카오, 구글) 구현

2023-04-22 07:01 UTC, Hyesooo commented on build.gradle
>      // lombok
이 코드 패치는 스프링 부트 애플리케이션에 OAuth2 클라이언트를 추가하는 것입니다. 

보안 및 웹 스타터와 유효성 검사 스타터의 종속성과 함께 'spring-boot-starter-oauth2-client' 종속성이 추가되었습니다.

버그 위험성은 현재 이 코드 패치에서 확인되지 않습니다. 그러나 일반적으로는 어노테이션 처리기에 대한 설명이 누락되어 있습니다. 이 정보는 일부 어노테이션을 사용할 때 문제를 방지하는 데 도움이 됩니다.

개선 제안으로는, 코드 패치에 대한 추가 정보, 예를 들어 해당 애플리케이션에서 OAuth2 클라이언트가 어떻게 사용되는지 더 나은 이해를 돕는 주석을 추가할 수 있습니다.

2023-04-22 07:02 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/AcoeApplication.java
>  }
이 코드 패치에서는 `@SpringBootApplication` 어노테이션에 `scanBasePackages` 속성이 추가된 것을 볼 수 있습니다. 이 속성으로 "com.aluminium.acoe.sys.config.properties" 패키지의 구성 속성을 스캔하게 됩니다.

이 코드 패치에는 버그 리스크는 보이지 않지만, 개선 제안으로는 `scanBasePackages` 속성값을 더 명확하게 설정하는 것이 좋겠습니다. 예를 들어, 그룹명이나 프로젝트명 등과 같이 더 완벽한 패키지 경로를 사용하여 해당 패키지를 지정하는 것이 좋습니다.

2023-04-22 07:02 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/api/controller/user/UserController.java
> +}
이 코드는 유저 정보를 반환하는 API의 컨트롤러 클래스입니다. 

향상 제안:
- 현재는 예외 처리가 없으므로 null 값을 다루지 못하는 상황이 발생할 가능성이 있습니다. 예외 처리가 필요합니다.
- `getUser` 메서드의 반환값으로 `ApiResponse` 를 사용하고 있습니다. 이 응답 객체에서 성공 여부를 확인할 수 있는 방법이 필요합니다.
- 컨트롤러의 URL 주소는 `/api/v1/users`로 되어 있습니다. 일반적으로 `users` 대신 `me`라는 경로를 사용하며 `GET /api/v1/me` 처럼 자신을 조회하는 API는 이와 같이 작성됩니다.

버그 위험
- `UserService` 에서 예외 정의가 동일한 오류(`RuntimeException`)를 사용하면 알아보기 힘든 버그가 발생할 가능성이 있습니다. 

안전 견고성 향상
- 인증과 권한 관리를 위해 Spring Security를 사용하는 경우 변경될 수 있는 인증/권한 시나리오를 예측하여 테스트 해야 합니다.
- lombok 어노테이션을 사용하고 있어 런타임 프로파일링시 가독성 저하가 일어날 가능성이 있으니 적극적인 운영  전략이 필요합니다.

2023-04-22 07:02 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/api/entity/auth/AuthReqModel.java
> +}
이 코드패치는 com.aluminium.acoe.sys.api.entity.auth 패키지에 AuthReqModel 클래스를 추가합니다. 

Lombok 애노테이션을 사용하여 getter, setter 및 인자 없는 생성자와 인자가 있는 생성자를 자동으로 생성합니다. 

버그의 위험성은 감지되지 않습니다. 그러나 개선 사항으로는 기본 생성자에 대한 javadoc 주석을 추가하는 것이 좋습니다. 또한 세터(setter) 메소드를 이 클래스 외부에서 사용하지 못하도록 제한하는 것이 좋을 수 있습니다.

2023-04-22 07:03 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/api/entity/user/User.java
> +}
이 코드조각은 User 엔티티를 정의하는 자바 클래스입니다. 이 코드는 큰 문제가 없어 보입니다. 

개선 제안으로는 password 필드가 JSON 응답에서 제외됨을 나타내는 @JsonIgnore 어노테이션이 있습니다. 따라서 이러한 경우에는 JSON Property 애너테이션을 사용하여 어노테이션을 대체할 수 있습니다. 예를 들어 `@JsonProperty(access = JsonProperty.Access.WRITE_ONLY)` 와 같이 사용할 수 있습니다. 

또한, 생성자에서 password 및 email 필드 값의 기본값을 설정하는 것이 좋습니다. 이렇게하면 응용 프로그램에서 null 값을 다루지 않아도 되기 때문입니다. 

마지막으로 createdAt과 modifiedAt 필드를 LocalDateTime 타입으로 저장한다는 점이 눈에 띕니다. 그러나 이 경우 다른 기본 형식으로 변환되어야 하는 경우가 많습니다. 이 연도와 시간 값을 데이터베이스가 인식하는 Datetime 형식으로 변환해 주는 방법 등을 알아봐야 합니다.

2023-04-22 07:03 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/api/entity/user/UserRefreshToken.java
> +}
이 코드 조각은 UserRefreshToken 이라는 JPA 엔티티를 정의합니다. 해당 엔티티에는 refresh token의 정보가 포함되어 있습니다. 

이 코드는 잘 작성된 것 같습니다. 그러나 몇 가지 개선할 수 있는 부분도 있습니다.

1. refreshTokenSeq는 현재 코드에서 사용되지 않으므로, 필요하지 않은 경우 삭제하는 것이 좋습니다.

2. com.aluminium.acoe.sys.api.entity.user 패키지 경로를 단순화하여 더 적합한 위치에 저장하는 것도 좋습니다.

3. 생성자의 매개변수로 유효성 검사 어노테이션을 추가하면 코드 안정성을 높일 수 있습니다.

4. 암호화 및 보안과 관련된 문제도 고려해보시기 바랍니다.

이 코드는 보안적으로 민감한 정보와 관련됩니다. 따라서 다른 모든 코드와 마찬가지로 보안취약점 점검, 테스트, 비지니스 요구사항 충족 여부 확인 등을 수행해야 합니다.

2023-04-22 07:03 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/api/repository/user/UserRefreshTokenRepository.java
> +}
위 코드 패치는 UserRepository 인터페이스를 상속받아 UserRefreshToken 엔티티와 관련된 JpaRepository를 구현하고 있습니다. 메서드 이름과 타입 모두 적절합니다.

단, findByUserIdAndRefreshToken 메서드의 경우에는 userId와 refreshToken을 모두 이용하여 UserRefreshToken 엔티티를 검색하는데, userId만 사용하여 검색하는 findByUserId 메서드가 이미 존재하기 때문에 불필요한 중복이 있습니다. 따라서 findByUserIdAndRefreshToken 메서드 대신 userId와 일치하는 UserRefreshToken 엔티티들을 모두 조회한 후, 그 결과에서 refreshToken이 일치하는 엔티티를 찾도록 변경하는 것이 더 적절할 것입니다.

추가적으로, 메서드 주석 또는 문서화가 없으므로 해당 메서드들이 어떤 역할을 하는지 쉽게 파악하기 어렵다는 점을 개선할 필요가 있습니다.

2023-04-22 07:04 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/api/repository/user/UserRepository.java
> +}
위 코드 패치에 대한 간단한 코드 리뷰를 도와드리겠습니다.

위 코드는 User 엔티티에 접근하는 JpaRepository 인터페이스를 구현한 UserRepository 인터페이스입니다. 해당 Repository에서는 findByUserId 메소드를 선언하여 사용자의 ID 값으로 검색된 User 엔티티를 반환합니다.

이 코드에 대한 버그나 위험이 보이지는 않습니다. 그러나 개선 사항으로는 다음과 같은 것들이 있을 수 있습니다:

- 메소드 이름이 getUserId로 더 일반적인 이름으로 변경되면 좀 더 읽기 쉬운 코드가 될 수 있습니다.
- JPA 엔티티 매핑 설정을 추가하여 User 엔티티를 데이터베이스 테이블에 매핑해야 합니다.
- 특정 기술 스택에 따라 UserRepository가 사용될 때 몇몇 최적화 작업을 수행할 수도 있습니다.

코드에 대한 전반적인 내용을 고려했을 때, 현재 코드는 완벽하게 동작할 수 있도록 미리 작성된 것입니다.

2023-04-22 07:04 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/api/service/UserService.java
> +}
이 코드 패치는 UserService 클래스를 정의하고 UserRepository에서 특정 userId에 해당하는 사용자 정보를 가져오는 getUser 메소드를 포함합니다. 
유용한 기능일 수 있습니다. 그러나 다음과 같은 개선 제안이 있습니다.

- 유저가 존재하지 않는 경우 처리 추가: 만약 입력된 userId에 해당하는 유저가 없는 경우 null을 반환할까요? 이 경우 클라이언트가 예외 처리를 할 필요가 있습니다. 만약 User 객체에 대해 Optional로 반환하여 유저가 없는 경우 빈 결과를 반환하면 좋을 것 같습니다.
- 로깅 추가 : 이 서비스가 기록되지 않으면 나중에 문제를 해결할 때 부연 설명 할만한 자료가 없을 수 있습니다. 따라서, log4j 또는 java.util.logging 등 여러 가지 로깅 프레임워크 중 하나를 사용하여 작업 로그를 생성해 주세요.
- 변수 이름 변경 : "userRepository"라는 이름은 충분히 이해 가능하지만, 논리적으로 더 명확한 이름으로 변경하는 것이 좋을 수 있습니다. 

위 내용들을 참고해 주시기 바랍니다.

2023-04-22 07:05 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/common/ApiResponse.java
> +}
이 코드 패치는 ApiResponse 클래스를 정의하고 세 개의 성공, 실패, 토큰 관련 응답 유틸리티 메서드를 제공합니다. 

이미 사용된 자바 라이브러리인 Lombok을 활용하여 생성자와 getter도 간단히 정의되어 있습니다. 또한 ApiResponseHeader와 ApiResponse<T>를 포함하며 ApiResponseHeader는 HTTP 상태 코드 및 메시지를 유지하고 body는 요청 결과 데이터 Map입니다.

버그 위험이라면 return new ApiResponse(new ApiResponseHeader(SUCCESS, SUCCESS_MESSAGE), map);와 같은 구문에서 ApiResponse 클래스에 T 형식 인수가 정의되어 있기 때문에 <T>를 생략해서는 안 됩니다.

개선을 위해서는 ApiResponse 클래스의 RESTful API에서 보다 빈번하게 발생하는 일반적인 오류 유형의 처리를 고려해볼 수 있다는 점입니다. 예를 들어, 잘못된 요청 또는 권한이 없는 요청 등에 대한 다양한 HTTP 응답(GUI 뿐만 아니라 API 클라이언트쪽에서도)을 포함하여 시스템 사용자 경험의 향상을 도모할 수 있습니다.

2023-04-22 07:05 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/common/ApiResponseHeader.java
> +}
이 코드 멋지게 작성되었습니다. 하지만 리뷰어로서 몇 가지 제안사항을 드리면,

1. 아래와 같이 `@AllArgsConstructor` 대신 `@RequiredArgsConstructor` 어노테이션을 사용하면, 초기에 주입되지 않은 final 필드값에 대해서도 생성자를 생성해줍니다.

```java
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

@Setter
@Getter
@RequiredArgsConstructor
public class ApiResponseHeader {
    private final int code;
    private final String message;
}
```

2. 초기화가 되지 않은 변수는 null 값을 가질 수 있습니다. 이러한 변수에 대해서 NullPointerException이 발생할 가능성이 있습니다. 따라서, 선언 시 default 값을 설정하시길 권장합니다.

```java
@Setter
@Getter
@AllArgsConstructor
public class ApiResponseHeader {
    private int code = 0;
    private String message = "";
}
```

3. 클래스를 더욱 쉽게 사용할 수 있도록 toString 메소드를 오버라이딩하여 추가하는 것이 좋습니다.

```java
@Setter
@Getter
@AllArgsConstructor
public class ApiResponseHeader {
    private int code = 0;
    private String message = "";

    @Override
    public String toString() {
        return "ApiResponseHeader{" +
                "code=" + code +
                ", message='" + message + '\'' +
                '}';
    }
}
```

위와 같은 방안으로 개선이 가능합니다.

2023-04-22 07:05 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/config/properties/AppProperties.java
> +}
이 코드는 Lombok을 사용하여 Spring Boot 속성으로 구성된 앱의 인증 및 OAuth2 토큰 설정에 대한 프로퍼티를 정의하는 클래스인 AppProperties를 생성합니다.

이 코드는 현재 버그나 오류가 없어 보입니다. 그러나 향후 변경 사항이 있을 수 있으므로 주기적으로 검토해야 합니다. 

개선 제안:
- OAuth2 authorizedRedirectUris 메서드에서 builder 패턴을 사용하면 좋을 것 같습니다.
- 변수 이름을 보다 명확하게 지정할 수 있다면 이해하기 쉬울 것입니다.

2023-04-22 07:06 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/config/properties/CorsProperties.java
> +}
이 코드는 CORS 설정에 대한 Spring Boot 프로퍼티 파일을 정의하는 클래스입니다. 이 클래스는 lombok 애노테이션을 사용하여 코드를 간결하게 유지합니다. 

모든 필드는 문자열이며, maxAge 필드는 롱 타입으로 선언됩니다. 

코드 리뷰에서 특별한 버그 위험 사항은 없습니다. 그러나 이 클래스의 개선을 위해서는 다음과 같은 점을 고려할 수 있습니다.

- allowedOrigins, allowedMethods 및 allowedHeaders가 쉼표로 구분된 문자열 목록인 경우, 배열 또는 List<String>으로 변경할 수 있습니다.
- prefix 속성 값이 하드 코딩되어 있기 때문에 상수로 정의하여 중복을 방지할 수 있습니다. 

이러한 개선 사항은 코드를 더 확장 가능하고 유지 관리하기 쉽게 만들어줄 수 있습니다.

2023-04-22 07:06 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/config/security/JwtConfig.java
> +}
위 코드는 JWT(Json Web Token)의 패키지와 OAuth 토큰 인증을 위한 코드입니다. 

코드 리뷰를 진행하며 발견된 문제와 개선 사항은 다음과 같습니다.

개선 사항:
- 변수명이 명확하지 않습니다. `secret`보다는 `jwtSecret`와 같은 변수명으로 변경하는 것이 좋습니다.
- 이 코드에서 필요한 메소드가 하나뿐인데도 불구하고 `@Configuration` 어노테이션을 사용하고 있습니다. 이럴 경우 컴파일 시간과 실행 시간 모두 오버헤드가 발생할 수 있으므로, `@Component`나 `@Service` 등 적절한 어노테이션을 사용하는 것이 좋습니다.

문제점:
- 이 코드에 큰 문제점은 보이지 않습니다. 
- 다만, `jwt.secret` 값을 외부에서 설정해야 합니다. 그래서 해당 값을 `application.properties` 등 외부 환경 파일에 설정하는 것이 권장됩니다.

2023-04-22 07:06 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/oauth/entity/ProviderType.java
> +}
이 코드 패치는 OAuth 인증 시스템에 사용될 ProviderType이라는 열거형(Enumeration) 클래스를 생성합니다. 

버그가 없어 보입니다. 

다만 개선하면 좋을 점은, 늘 그렇듯이 네이밍과 주석에 더 신경쓰면 됩니다. Enum 클래스의 이름과 값들(GOOGLE, KAKAO, LOCAL)은 시스템에서 사용되는 용어나 언어와 일관성 있게 설정하는 것이 좋습니다. 또한 이 클래스와 각 항목의 역할과 기능을 설명하는 명확하고 자세한 주석을 추가하여 읽기 쉽고 유지보수하기 쉬운 코드를 만드는 것이 좋습니다.

2023-04-22 07:07 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/oauth/entity/RoleType.java
> +}
이 코드는 알루미늄 회사에서 사용하는 OAuth 엔티티 클래스 중 하나인 RoleType 클래스입니다. 

이 클래스는 각각의 역할에 대한 정보를 나타내는 열거형(Enum)으로 구성되어 있습니다.

코드 리뷰를 통해 개선 및 버그를 방지할 수 있는 권장 사항은 다음과 같습니다.

- 생성자가 빠진 경우와 new 연산자를 통한 객체 생성을 금지하여 안전성을 강화한다.
- 생성자 파라미터에서 'code'와 'displayName'를 구분하여 한글 가능 여부를 명시한다.
- 열거형의 모든 항목을 순회하는 로직에서 예외처리를 추가하여 잘못된 코드 값을 줄일 수 있다.

2023-04-22 07:07 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/oauth/entity/UserPrincipal.java
> +}
이 코드에 대한 개요는 다음과 같습니다:

- UserPrincipal 클래스는 OAuth2User, UserDetails 및 OidcUser를 구현합니다.
- UserPrincipal 클래스는 인증 된 사용자의 기본 정보를 포함하며, 사용자 이름, 패스워드 및 권한 등이 있습니다.
- create 메소드를 사용하여 UserPrincipal 객체를 생성할 수 있습니다. 이를 위해서는 User객체와 함께 사용 될 수 있는 설명을 담은 Map<String,Object> attribute를 매개 변수로 전달해야합니다.

해당 코드에서 추가적인 개선사항은 없어보이지만, 다음과 같은 수정 사항이 있습니다.
- getIdToken() 및 getUserInfo() 메서드는 null 값으로 반환하고 있습니다. 이 메서드를 수정하여 해당 값을 반환할 필요가 있습니다.
- create 메서드는 모든 사용자의 역할을 "USER" 로 지정하지만, 각 사용자에 따라 다른 역할이 있을 수 있습니다. 이것은 고려해 볼 점이 됩니다.

또한 지금은 코드 리스크를 평가할 길이 없습니다. 현재 작성 중인 시점에서 소프트웨어 버그는 언제든지 발생할 가능성이 있습니다..

2023-04-22 07:07 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/oauth/exception/OAuthProviderMissMatchException.java
> +}
이 코드 패치는 OAuthProviderMissMatchException이라는 새로운 예외 클래스를 정의하는 Java 파일입니다. RuntimeException을 확장하고, 메시지를 파라미터로 받아 생성자를 정의합니다.
이 코드는 큰 문제가 없어보이며, 예외 클래스를 정의하는 데 필요한 정보만 포함하고 있습니다. 그러나 개발자가 해당 예외를 발생시키는 코드 작성 시 어떤 경우에 이 예외가 발생하는지 세부 정보를 추가하는 것이 좋을 수도 있습니다.

2023-04-22 07:07 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/oauth/exception/RestAuthenticationEntryPoint.java
> +}
이 코드는 Spring Security에서 인증 예외가 발생했을 때 처리하기 위한 클래스인 `RestAuthenticationEntryPoint`를 정의합니다. 코드 리뷰 결과에 따라 개선할 점과 버그 위험이 있을 경우 주석으로 제공하고자 합니다.

개선할 점:
- `authException.printStackTrace();` 로그 출력문은 필요하지 않습니다. 로그레벨을 debug로 낮추거나 삭제하는 것이 좋습니다.
- `authException.getLocalizedMessage()` 대신 `authException.getMessage()`를 사용하는 것이 좋습니다. `getLocalizedMessage()`는 `getMessage()`와 동일한 값을 반환하지만, 해당 오류 메시지가 지원되는 로케일 언어가 있는 경우 지원되는 로케일 언어의 메시지를 반환할 수도 있습니다.

버그 위험:
현재 이 코드에서는 큰 문제가 발견되지 않았습니다. 다만, 시스템적으로 보면 Spring Security 업데이트 및 서브 모듈이 변화함에 따라 해당 코드도 변경되어야 하는 상황이 올 수 있습니다.

2023-04-22 07:08 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/oauth/exception/TokenValidFailedException.java
> +}
해당 코드는 새로운 패키지와 그 안에 TokenValidFailedException이라는 클래스를 추가하고 있습니다. 부모 클래스인 RuntimeException을 상속받아 오버라이드 없이 사용하고 있습니다.

클래스 내에 생성자가 두 개 존재하는데, 기본 생성자에서는 "Failed to generate Token."이란 메시지를 받아 부모 클래스의 생성자로 전달하게 됩니다. 다른 생성자는 private 제한자를 가지며, 해당 클래스 밖에서 호출될 일이 없도록 막혀져 있습니다.

코드에 대한 버그나 위험성은 보이지 않으며, 개선 목적으로 나열할 만한 것도 없어보입니다. 하지만 이 클래스를 사용하는 부분이 있을 경우 어떻게 사용되는지에 따라 개선 여지가 생길 수도 있습니다.

2023-04-22 07:08 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/oauth/filter/TokenAuthenticationFilter.java
> +}
해당 코드는 OAuth 인증 토큰을 받아와서 유효성 검사 후 시큐리티 컨텍스트 홀더에 인증 정보를 저장하는 필터입니다. 

- 버그 리스크: 보안적인 취약점이나 그 밖의 큰 버그는 보이지 않습니다.
- 개선 제안: 대부분의 코드가 간단하고, 의존성 주입(Dependency Injection)을 위해 롬복(@RequiredArgsConstructor)을 사용하여 보일러플레이트 코드를 줄이는 등 깔끔한 구현을 보입니다. 본인 프로젝트와 맞게 더욱 함수적으로 구현한다면 더 깔끔해질 것입니다.

2023-04-22 07:08 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/oauth/handler/OAuth2AuthenticationFailureHandler.java
> +}
이 코드는 OAuth2 인증 방식에서 실패했을 때 호출되는 핸들러 클래스입니다. 

코드 자체는 간단하며, 부적절한 요청에 대한 에러 메시지를 포함하여 URI 문자열을 만드는 UriComponentsBuilder를 사용하는 것은 좋습니다.

그러나 현재 코드를 볼 때 취약점이나 버그는 보이지 않습니다. 

개선 제안으로는 예외 처리를 좀 더 구체적으로 할 수 있습니다. 이 경우 개발자는 오류를 추적하고 수정할 때 알림을 받을 수 있습니다. 이 외에도 긴 시간에 걸친 저장소 접근문제가 일어날 수 있기 때문에 authorizationRequestRepository에 캐시를 추가하는 것이 좋을 수 있습니다.

2023-04-22 07:09 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/oauth/info/OAuth2UserInfo.java
> +}
이 코드는 OAuth2를 사용하여 인증된 사용자의 정보를 가져오기 위한 추상 클래스인 OAuth2UserInfo를 정의합니다. 이 추상 클래스에는 Map<String, Object> 타입의 attributes 필드가 있으며 인증된 사용자의 정보를 저장합니다. 

이 클래스에서는 getId(), getName(), getEmail(), getImageUrl() 메서드 등을 제공합니다. 하위 클래스는 이러한 메서드를 구현하여 실제 인증 공급자(provider)에서 얻은 사용자 정보를 반환할 수 있습니다.

개선 제안:
- attributes 필드가 protected로 선언되어 있으므로 하위 클래스나 패키지 외부에서 직접적으로 접근할 수 있기 때문에 private으로 변경하는 것이 안전합니다.
- 한 번 생성된 OAuth2UserInfo 객체의 attributes 항목은 수정될 일이 없으므로 final 로 선언하여 불변성을 보장하는 것도 좋습니다.

2023-04-22 07:09 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/oauth/info/OAuth2UserInfoFactory.java
> +}
이 코드는 OAuth 인증 정보를 생성하는 팩토리 클래스입니다. ProviderType(GOOGLE 또는 KAKAO)와 가공할 Map 데이터를 받아서 providerType에 따라 적절한 인증 정보 객체(GoogleOAuth2UserInfo 또는 KakaoOAuth2UserInfo)를 생성하여 반환합니다.

개선 제안:

1. 현재 코드에서는 GOOGLE과 KAKAO 두 개의 ProviderType만 처리하고 있습니다. 이외의 다른 ProviderType이 추가되거나 삭제될 경우 해당 부분을 수정해주어야 합니다. 새로운 ProviderType이 추가될 때마다 새로운 case를 추가하여 switch문을 수정하기 번거로워지므로, 추후 유연하게 대처하기 위해 Reflection 등 다른 방식으로 구현하는 것을 고려해 볼 수 있습니다.

2. 예외 발생 시 Exception 메시지가 "유효하지 않음"으로 고정되어 있으며, 사용자가 원인을 파악하기 어렵습니다. 예외 메시지를 보다 상세하게 작성하여 사용성을 향상시킬 수 있습니다.

3. null 체크가 되어 있지 않으므로 attributes에 null 값을 넣으면 NullPointerException이 발생할 수 있습니다. 이를 방지하기 위해 null 처리를 진행해 주어야 합니다.

2023-04-22 07:09 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/oauth/info/impl/GoogleOAuth2UserInfo.java
> +}
이 코드는 Google OAuth2 사용자 정보를 가져오기 위한 클래스입니다.  

이 클래스는 OAuth2UserInfo 추상 클래스를 상속합니다. 

OAuth2UserInfo 클래스는 ID, 이름, 이메일 및 프로필 이미지 URL과 같은 OAuth2 공급자에서 가져온 사용자 정보의 일부를 얻을 수 있도록하는 방법을 지정합니다.

GoogleOAuth2UserInfo 클래스는 Google에서 반환된 JSON 맵에 있는 세부 정보를 가져오는 네 개의 메소드 (getId, getName, getEmail 및 getImageUrl)를 구현합니다.

이 코드의 기능상 문제점은 없어 보입니다. 그러나 메소드 또는 변수 이름에 대한 일관성있는 컨벤션을 사용하는 것이 좋습니다. 또한 null 값 검사와 같은 데이터 유효성 검사를 추가하는 것이 좋습니다.

2023-04-22 07:10 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/oauth/info/impl/KakaoOAuth2UserInfo.java
> +}
이 코드는 OAuth2UserInfo 인터페이스를 구현하는 KakaoOAuth2UserInfo 클래스입니다. 이 클래스는 카카오 로그인 API에서 가져온 사용자 정보를 처리합니다.

이 코드에서 주요한 위험성은 attributes 매개변수가 null일 수 있다는 점입니다. getId(), getName(), getEmail() 및 getImageUrl() 메소드는 모두 attributes 매개변수를 사용합니다. 따라서 매개변수가 null인 경우 compile-time 에서 오류가 발생하며, null pointer exception 같은 런타임 오류가 발생합니다. 따라서 null 체크를 추가하여 이 문제를 해결할 수 있습니다.

이 코드에서 개선할 점은 반환 값을 사용하는 곳에서도 null 예외처리를 해야 한다는 것입니다. 이러한 예외 처리는 클라이언트 코드에서 누락될 수 있으므로 클래스 내부에서 null 예외 처리를 수행하는 것이 좋습니다.

2023-04-22 07:10 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/oauth/repository/OAuth2AuthorizationRequestBasedOnCookieRepository.java
> +}
이 코드는 OAuth2 로그인을 위해 쿠키를 사용하는 스프링 시큐리티의 AuthorizationRequestRepository를 구현합니다. 자바 서블릿 API와 Spring Security OAuth2 core 패키지에서 제공하는 클래스를 사용합니다.

이 코드에 대한 개선점 및 버그 리스크는 다음과 같습니다.

- 쿠키의 만료시간을 상수로 정의하여 더 큰 유연성을 부여할 수 있습니다.
- 적절한 예외 처리 코드가 없으므로 예외 발생에 대한 대응 코드 추가 필요합니다.
- 적절한 테스트 코드가 없므로 테스트 코드 작성이 필요합니다.

2023-04-22 07:10 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/oauth/service/CustomOAuth2UserService.java
> +}
이 코드는 CustomOAuth2UserService 파일로 구성된 OAuth2 인증에 대한 사용자 서비스를 나타내며, OAuth2UserRequest 및 OAuth2User를 기반으로하는 로그인 기능의 처리를 표현합니다. 

개선할 사항:
- 프린트스택을 제거하고 대신 로그 (logger)를 사용해야 합니다.
- OAuth2UserInfoFactory.getOAuth2UserInfo () 메소드는 null에 대한 예외처리가 추가되어야 합니다.

위험한 버그는 없어 보입니다.

2023-04-23 02:05 UTC, Hyesooo requested changes
권한과 계정관련 로직이 까다로우셨을 텐데 수고많으셨습니다. 
커맨트 하나하나 남겨뒀으니 확인 부탁드리고, chat-gpt 리뷰도 참고하면 좋을 것 같습니다.
다만 한가지 **꼭** 부탁드리고 싶은 점이 있는데,
작업단위(이슈단위)가 너무 커서 실제 한 번에 올라오는 **코드 양이 너무 많습니다.**
알아보기도 힘들고 리뷰를 진행하는게 너무 어려워서 **꼭꼭꼭** 이슈(작업)단위를 세분화 부탁드립니다. 
((이 PR도 사실 제대로 분석 못한 듯....ㅎㅎ ㅠㅠ))


아래에 전반적으로 수정/논의/당부할 사항 적어두었으니 확인해주세요.

[수정사항]
- 모든 API에 대해 스웨거 주석 추가(어노테이션 사용)
- 엔티티에 대해 물리ID와 의미있는 ID를 혼용해서 쓰는것(User.java의 userSeq vs userId)
- 예외에 대한 처리(common.api.code, common.api.response 패키지 사용하도록 수정)
- 예외 핸들러에 대한 처리(글로벌 핸들링할 예외들인지 여부에 따라 패키지 이동 및 로직 수정)

[권장사항]
- javaDoc 주석 추가(alt 누르면 add javaDoc 자동으로 추가해줍니당)

감사합니다 :)

2023-04-23 02:05 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/AcoeApplication.java
> +@SpringBootApplication(scanBasePackages = {"com.aluminium.acoe.sys.config.properties"})
이렇게하면 해당 패키지 하위만 컴포넌트 스캔 대상이 될텐데, 그럼 다른 패키지에 있는 빈이 스캔되지 않을거라... 서버 올릴때 에러 안 났나요?

2023-04-23 02:05 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/api/controller/auth/AuthController.java
> +    @GetMapping("/refresh")
모든 API는 문서화될 수 있게 스웨거 어노테이션 꼭 추가해주세요.(프론트에서 유정님이 볼 수 있도록)

2023-04-23 02:05 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/api/entity/user/User.java
> +    private String password;
패스워드 암/복호화 안하나요? 한다면 어떤 알고리즘 사용하시는지..!?!

2023-04-23 02:05 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/api/entity/user/User.java
> +    private String userId;
userSeq와 userId의 차이가 뭘까요? 둘 중 하나만 사용하는게 낫지 않을까요? (비즈니스 로직과 관련없는 물리ID인 듯한 userSeq가 더 나아보입니당 그리고 String 비교연산보다 숫자 비교 연산이 더 경제적 이기도 하고..!)

2023-04-23 02:05 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/common/ApiResponse.java
> +
이 클래스 글로벌 예외 처리하면서 common > api > response에 생성해 뒀습니다.
저희 프로젝트에서는 해당 클래스 이용해서 통신하면 될 듯합니다.

2023-04-23 02:05 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/common/ApiResponse.java
> +
추가적으로 필요한 예외가 있으시면 common > api  하위의 code 패키지와 response 패키지 수정해서 사용 바랍니다.

2023-04-23 02:05 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/common/ApiResponseHeader.java
> +public class ApiResponseHeader {
마찬가지로 common.api 패키지 이용하시면 됩니다.

2023-04-23 02:05 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/oauth/entity/RoleType.java
> +public enum RoleType {
enum은 entity 패키지 말고 따로 enum패키지를 만들어 포함시키는게 나아 보입니다.

2023-04-23 02:05 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/oauth/entity/UserPrincipal.java
> +package com.aluminium.acoe.sys.oauth.entity;
실제 entity가 아닌 파일들에 대해서는 패키지 정리가 필요해보입니다.

2023-04-23 02:05 UTC, Hyesooo commented on src/main/java/com/aluminium/acoe/sys/oauth/handler/OAuth2AuthenticationFailureHandler.java
> +package com.aluminium.acoe.sys.oauth.handler;
이 예외가 컨트롤러 api 호출로 인해 발생하는 예외라면 common.exception.globalExceptionHandler에 넣어야하는데, 필터 단에서 발생하는 에외인가요? 
그리고 그 밖에 커스텀한 exception들의 패키지 위치도 common.exception에 넣을 지 sys에 넣을지 논의가 필요해 보입니다.

2023-04-29 10:29 UTC, Hanseunghoon commented on src/main/java/com/aluminium/acoe/AcoeApplication.java
> +@SpringBootApplication(scanBasePackages = {"com.aluminium.acoe.sys.config.properties"})
특정 프로퍼티를 못 가져오는 이슈가 있어서 해결법을 찾아보니 저렇게 스캔해야하는 패키지를 등록해주면 된다고 하더라구요! 로컬에서는 혜수님 코드포함해서 실행했을때 문제는 없었습니다!

2023-04-29 10:29 UTC, Hanseunghoon commented on src/main/java/com/aluminium/acoe/sys/api/controller/auth/AuthController.java
> +    @GetMapping("/refresh")
넵 swaggers는 추가 예정입니다!

2023-04-29 10:33 UTC, Hanseunghoon commented on src/main/java/com/aluminium/acoe/sys/api/entity/user/User.java
> +    private String userId;
seq는 회원정보 저장한 순(가입순으로)으로 시퀀스를 부여하고, id는 로그인 id입니다!! (소셜 계정 이메일등)

2023-04-29 10:35 UTC, Hanseunghoon commented on src/main/java/com/aluminium/acoe/sys/api/entity/user/User.java
> +    private String password;
`    @Bean
    public BCryptPasswordEncoder passwordEncoder() {
        return new BCryptPasswordEncoder();
    }`
입니다!

2023-04-29 11:21 UTC, Hanseunghoon commented on src/main/java/com/aluminium/acoe/sys/oauth/handler/OAuth2AuthenticationFailureHandler.java
> +package com.aluminium.acoe.sys.oauth.handler;
소셜로그인 관련한 예외라 별도 패키지에 넣어두긴했습니다..!

2023-04-29 12:05 UTC, Hyesooo commented on build.gradle
>      // lombok
이 코드 패치의 목적은 Spring Boot 프로젝트에 OAuth2 클라이언트를 위한 의존성을 추가하는 것입니다. 

이 변경사항 자체에는 버그의 위험이 없어 보이지만, 애플리케이션 전체를 고려할 때 스프링 시큐리티 설정 등에서 직면할 수 있는 취약점과 보안 문제가 존재할 수 있습니다. 따라서 이 변경 사항이 다른 부분과 정확히 통합되는지 확인해야합니다.

추가 제안으로는 의존성 버전 관리 및 최신 버전 사용 여부를 검토하고, 코드의 가독성과 유지보수성을 높이기 위해 필요한 경우 주석을 추가하거나 코드 구조를 개선하는 것이 있습니다.

2023-04-29 12:52 UTC, merged